import SinglePost from "@/components/SinglePost";
import { getAllPosts, getPostsForTopPage } from "@/lib/notionAPI";
import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    // paths: pathsと同じ意味
    paths: [
      { params: { page: "1" } },
      { params: { page: "2" } },
      { params: { page: "3" } },
      { params: { page: "4" } },
    ],
    fallback: "blocking", // 404ページを表示するまで待つ
  };
};

export const getStaticProps: GetStaticProps = async () => {
  const fourPosts = await getPostsForTopPage();

  return {
    props: {
      fourPosts,
    },
    // ISR (Incremental Static Regeneration) 1時間ごとに内容を更新する
    revalidate: 60 * 60,
  };
};

const BlogPageList = ({ fourPosts }: { fourPosts: any }) => {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">Notion Blog</h1>
        <section className="sm:grid grid-cols-2 w-5/6 gap-3 mx-auto">
          {fourPosts.map((post: any) => (
            <div key={post.id}>
              <SinglePost
                title={post.title}
                description={post.description}
                date={post.date}
                tags={post.tags}
                slug={post.slug}
                isPaginationPage={true}
              />
            </div>
          ))}
        </section>
      </main>
    </div>
  );
};

export default BlogPageList;
