import { getAllPosts } from "@/lib/notionAPI";
import Head from "next/head";

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();

  return {
    // allPosts: allPostsと同じ意味
    props: {
      allPosts,
    },
    // ISR (Incremental Static Regeneration) 60秒ごとに内容を更新する
    revalidate: 60,
  };
};

export default function Home({ allPosts }: { allPosts: any }) {
  console.log(allPosts);

  return (
    <div>
      <Head>
        <title>My page title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
